### ISSUE TITLE
Metamasck's Astar snap won't let me transfer my ASTR tokens "The request timed out"

### ISSUE THREAD

**Issue by fr4ncinei** [AstarNetwork/metamask-snap-astar#8]
On 12/29/2023, I transferred my ASTR tokens to my Astar Snap wallet connected to Metamasck, since then I have not been able to transfer the tokens anywhere, I have tried everything. The same error always appears: "The request timed out"

![Captura de tela 2024-01-03 225309](https://github.com/AstarNetwork/metamask-snap-astar/assets/155597463/14969de8-d9b8-4fd1-9d4e-6b691c0510b6)
![Captura de tela 2024-01-03 230042](https://github.com/AstarNetwork/metamask-snap-astar/assets/155597463/57b3fb30-2bb8-4560-8489-143de6b6b6eb)

**Comment by gluneau** [comment]
Hello @fr4ncinei, It does works for me. Can you try again and include any logs you get in the developer's console?
